### ISSUE TITLE
Startup Crash

### ISSUE THREAD

**Issue by keraldi** [Sunconure11/compitum-magia-issues#10]
Full latest pack release:

https://paste.dimdev.org/naxoqahamo.mccrash

Without Animania:

https://paste.dimdev.org/fewuvejeca.mccrash

Without Animania, Blood Magic & dependants:

https://paste.dimdev.org/ejatawurih.mccrash

Without all of the above + Ceramics:

https://paste.dimdev.org/cusohacapi.mccrash

I'll stop now.

**Comment by keraldi** [comment]
Most likely recipe syntax error.

**Comment by Sunconure11** [comment]
Same crash the other user was reporting. I literally don't know what's going on. I reported it to the animania devs.

**Comment by Sunconure11** [comment]
This fired before they tried pulling Animania.

**Comment by Sunconure11** [comment]
https://github.com/WayofTime/BloodMagic/issues/1529

https://github.com/capnkirok/animaniamod/issues/272

**Comment by keraldi** [comment]
Push, updated initial post with more error logs after disabling some of the mods.

Also, there are a lot of errors during startup (log exceeds 100k lines).

**Comment by keraldi** [comment]
[2019-01-27-3.log.gz](https://github.com/Sunconure11/compitum-magia-issues/files/2800594/2019-01-27-3.log.gz)
[2019-01-27-4.log.gz](https://github.com/Sunconure11/compitum-magia-issues/files/2800595/2019-01-27-4.log.gz)
[2019-01-27-5.log.gz](https://github.com/Sunconure11/compitum-magia-issues/files/2800596/2019-01-27-5.log.gz)
[2019-01-27-6.log.gz](https://github.com/Sunconure11/compitum-magia-issues/files/2800597/2019-01-27-6.log.gz)

**Comment by Sunconure11** [comment]
I'm fucking baffled. I just pushed out another update though. Since Ceramics seems to be being blamed too, I will push this over to them, as well.

**Comment by keraldi** [comment]
It is most likely a recipe modifying mod interacting with all of them.
Or a syntax error that is loaded by all of them.

Especially if they are loaded in alphabetical order.

**Comment by Sunconure11** [comment]
I believe I know how to find the cause, but you will need to fill your reports more. Delete reliquary, and keep deleting more and more causative mods. When it boots, log the last mod pulled. Also post all crash reports, even if they look the same.

I pushed out an update recently, try it on that.

**Comment by Sunconure11** [comment]
Due to a bout of illness and me being unable to replicate this, I'd advise you keep me informed. It's clear the bug is happening, but I am unable to replicate it.

**Comment by keraldi** [comment]
New version with everything:
https://paste.dimdev.org/tudopufonu.mccrash

Seeing as the error remains the same, I'll fast forward.
I tried one run without CraftTweaker + dependents to rule it out, crash is the same as with everything.

Without all of the above + Reliquary:
No crash.
Player Choice screen opens with "Example Mod" on the left side.
Pressing done quits the game (without crash log).

Tried it again without changing anything:
https://paste.dimdev.org/fayupohigu.mccrash

... this feels like a waste of time.

**Comment by keraldi** [comment]
Removing Tough As Nails in addition to all of the above, I get to the main menus.

**Comment by Sunconure11** [comment]
If it is TaN, I believe I know the file to blame, but it is strange since I would have run into it too.

**Comment by keraldi** [comment]
It might be something completely unrelated to the individual mods.

**Comment by Sunconure11** [comment]
I believe the file at fault is drink_stats.json. Try running the pack with all mods, but remove that file.

**Comment by keraldi** [comment]
Change your "I believe" to "I think" and you were thinking correctly.
Removing "./config/toughasnails/drink_stats.json" fixes the issue.
I was able to start up the game.

**Comment by Sunconure11** [comment]
Welp, I'm going to have to remake that file later, then.
